@baseUel = http://localhost:3000
# @ip = http://192.168.199.123:8080
@ip = http://192.168.0.102:8080

@json = Content-Type: application/json

###
POST  {{ip}}/api/user/register
{{json}}

{
  "username": "123456",
  "password": "123456"
}

###
GET {{ip}}/api/user/all

# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3Q1IiwiaWF0IjoxNTYxMjE1NzQ4LCJleHAiOjE1NjEyMTkzNDgsImlzcyI6IlRoaW5rQmlnIn0.lAsCT42QUKhPZ0fdJq464d2UzMlJalsqFMMDRNE1tqU
 
###
POST {{ip}}/api/user/login
{{json}}

{
  "_id": "5d0dbf69c4917345242b6ecb",
  "username": "test1",
  "password": "123456"
}

###
POST   {{ip}}/api/user/pwdchange
{{json}}

{
  "username": "hahaha",
  "currentPwd": "123456789",
  "newPwd": "123456789"
}